config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"
  resources :offers do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings

  include PgSearch::Model
    pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :offers
         has_many :bookings_as_owner, through: :offers, source: :bookings
         has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_offer, only: [:new, :create, :show]

  def index
    # @offers = current_user.offer
    @bookings = current_user.bookings
    @bookings_owner = current_user.bookings_as_owner
  end

  def new
    @booking = Booking.new
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
      @booking.offer = @offer
      @booking.user = current_user
      if @booking.save
        redirect_to bookings_path
      else
        render :new
      end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    if params[:query].present?
      sql_query = <<~SQL
        offers.title @@ :query
        OR offers.description @@ :query
      SQL
      @offers = Offer.where(sql_query, query: "%#{params[:query]}%")
    else
      @offers = Offer.all
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end

    def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save!
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @offer = Offer.new
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :price, :location, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-10 offset-1 py-4">
      <h1>My trips</h1>
      <% @bookings.each do |booking| %>
        <div class="card-product mx-auto">
        <%= cl_image_tag booking.offer.photo.key.to_s, height: 300, width: 300, crop: :fill %>
          <div class="card-product-infos">
            <div class="information">
                <h2 class="mx-0"><%= booking.offer.title%></h2>
                <p><%= booking.offer.description %></p>
                <p>Booked from: <%= booking.start_date.strftime("%d.%m.%Y") %> until <%=  booking.end_date.strftime("%d.%m.%Y") %><em>(<%= (booking.end_date - booking.start_date).to_i %> days)</em></p>
                <p>Daily rate: € <%= number_with_precision(booking.offer.price, precision: 2) %></p>
            </div>
            <div class="total-price mt-2">
              <h6>Total price: € <%= number_with_precision((booking.end_date - booking.start_date).to_i*booking.offer.price, precision: 2) %></h6>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-10 offset-1 py-4">
        <h1>My booked offers</h1>
        <% @bookings_owner.each do |booking| %>
          <div class="card-product mx-auto">
            <%= cl_image_tag booking.offer.photo.key.to_s, height: 300, width: 300, crop: :fill %>
              <div class="card-product-infos">
                <div class="information">
                  <h2 class="mx-0"><%= booking.offer.title%></h2>
                  <p><%= booking.offer.description %></p>
                  <p>Booked from: <%= booking.start_date.strftime("%d.%m.%Y") %> until <%=  booking.end_date.strftime("%d.%m.%Y") %><em>(<%= (booking.end_date - booking.start_date).to_i %> days)</em></p>
                  <p>Daily rate: € <%= number_with_precision(booking.offer.price, precision: 2) %></p>
                </div>
              <div class="total-price mt-2">
                <h6>Total price: € <%= number_with_precision((booking.end_date - booking.start_date).to_i*booking.offer.price, precision: 2) %></h6>
              </div>
            </div>
          </div>
          <% end %>
          <div class="d-flex justify-content-center">
            <button type="button" class="main-btn mt-4 "><%= link_to "Back to offers", offers_path %></button>
          </div>
        </div>
      </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col pt-4 d-flex justify-content-start">
      <h1><%= @offer.title %></h1>
    </div>
    <div class="col pt-5 d-flex justify-content-end">
      <h4>€<%= @offer.price %>/night</h4>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex justify-content-start">
      <p>Located in: <%= @offer.location %>, Germany</p>
    </div>
    <div class="col d-flex justify-content-end">
      <p>Offered by: <%= @offer.user.name %></p>
    </div>
  </div>

  <div class="row offer-img" style="background-image: url('<%= cl_image_path @offer.photo.key %>')">
    <div class="col offer-btn">
      <div class="description-card">
      <%= @offer.description %>
      </div>
      <div class="description-card">
      <%= simple_form_for [@offer, @booking] do |f| %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.submit "Book now", class: "main-btn-book" %>
      <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>McVanRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/diafrrnkz/image/upload/v1677659233/favicon_dvluc4.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>

  <body>
     <%= render "shared/navbar" %>
      <div> <%= yield %> </div>
     <%= render "shared/footer" %>
  </body>
</html>

app/views/offers/index.html.erb
<div class="container-card px-4">
  <div class="d_flex py-5 px-5">
    <% @offers.each do |offer| %>
        <%= link_to offer_path(offer.id), class:"mb-1 text-decoration-none text-reset" do %>
          <div class="col card my-2">
            <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key.to_s, height: 300, width: 400, crop: :fill %>
            <% else %>
              <%= image_tag("https://res.cloudinary.com/diafrrnkz/image/upload/v1677750580/development/sd3me0792s8n3ux1rwuboqej5zec.webp", size: "400x300") %>
            <% end %>

              <div class="card-body">
                <h5 class="card-title"><%= offer.title %></h5>
                <p class="my-0"><%= offer.location %></p>
              </div>
              <div class="card-footer">
                <small class="text-muted"> € <%= number_with_precision(offer.price, precision: 2) %>/night</small>
              </div>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container justify-content-center w-50">
    <div class="row pt-4 pb-2">
      <h1>Add your offer</h1>
    </div>
    <div class="row">
      <%= form_with(model: @offer) do |f| %>
          <div class="card-offer card-body">
            <div class="mb-3">
              <%= f.label :title, { class: "form-label"} %>
              <%= f.text_field :title, { class: "form-control", placeholder: "Name of your offer" } %>
            </div>

            <div class="mb-3">
              <%= f.label :description, { class: "form-label"} %>
              <%= f.text_field :description, { class: "form-control", placeholder: "Describe your offer in a few sentences" } %>
            </div>

            <div class="mb-3">
              <%= f.label :price, { class: "form-label"} %>
              <%= f.text_field :price, { class: "form-control", placeholder: "Enter the nightly price" } %>
            </div>

            <div class="mb-3">
              <%= f.label :location, { class: "form-label"} %>
              <%= f.text_field :location, { class: "form-control", placeholder: "Enter your location" } %>
            </div>

            <div class="mb-3">
            <%= f.label :photo, { class: "form-label"} %><br>
            <%= f.file_field :photo, as: :file %>
            </div>
            <center>
            <%= f.submit "Submit", class: "main-btn mt-4 w-25" %>
            </center>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col pt-4 d-flex justify-content-start">
      <h1><%= @offer.title %></h1>
    </div>
    <div class="col pt-5 d-flex justify-content-end">
      <h4>€<%= @offer.price %>/night</h4>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex justify-content-start">
      <p>Located in: <%= @offer.location %>, Germany</p>
    </div>
    <div class="col d-flex justify-content-end">
      <p>Offered by: <%= @offer.user.name %></p>
    </div>
  </div>

  <div class="row offer-img" style="background-image: url('<%= cl_image_path @offer.photo.key.to_s %>')">
    <div class="col offer-btn">
      <div class="description-card">
       <%= @offer.description %>
      </div>
      <button type="button" class="main-btn"><%= link_to "Book now!", new_offer_booking_path(@offer.id) %></button>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Built with blood, sweat and tears by Alina, Andreia and MC!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex">
    <div class="container-logo justify-content-start">
      <a href="/offers"><img src="https://res.cloudinary.com/diafrrnkz/image/upload/v1677765296/New_Project_5_nzmdnv.png" width="387px"></a>
    </div>
    <div class="justify-content-center">
      <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="search-form-control form-group d-flex search-input">
          <%= form_with url: offers_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a van to rent"
            %>
            <%= submit_tag "Search", class: "search-btn" %>
          <% end %>
        </div>
      <% end %>
      </div>


      <%#<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> %>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/offers", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List a new offer", "/offers/new", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "View my bookings", "/bookings", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/122232541?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", "/bookings", class: "dropdown-item" %>
              <%= link_to "View my bookings", "/bookings", class: "dropdown-item" %>
              <%= link_to "List a new offer", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
         <%# <div class="flash flash-success alert alert-dismissible fade show" role="alert">
            <span><strong>Yay!</strong> 🎉 you successfully signed in to MCvanrental.</span>
              <a data-bs-dismiss="alert" aria-label="Close">
               <i class="fas fa-times"></i>
              </a>
        </div> %>
      </ul>
    </div>
  </div>
</div>